### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by tdossantos97** [3DIndian/Google-Context-Menu-Edge#4]
Virus reported by Windows defender

**Comment by 3DIndian** [comment]
I will check as soon as I return to college

**Comment by 3DIndian** [comment]
it doesn't show virus on my system, you can go through the source code if you want to verify the addon.
Thanks for the comment!

**Comment by tdossantos97** [comment]
Okay
That means I couldn't install it because of false positive reported by
Windows defender on Windows 10

Best regards.

**Comment by 3DIndian** [comment]
Yes!
